---
- name: restart nginx
  service: name=nginx state=restarted

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  service: name=nginx state=reloaded

- name: Enable nginx exporter service
  ansible.builtin.systemd:
    name: "nginx_exporter.service"
    enabled: yes

- name: Restart nginx exporter service
  ansible.builtin.systemd:
    name: "nginx_exporter.service"
    state: restarted